### ISSUE TITLE
A dataset with 'train' and 'valid' folders for (denoising/transforming) auto-encoders?

### ISSUE THREAD

**Issue by jbmaxwell** [utkuozbulak/pytorch-custom-dataset-examples#1]
I'm sure I'll figure it out, but I'm trying to build a dataset with two image folders, a 'train' folder for inputs, and a 'valid' folder for checking inputs against the model's output, on order to calculate the error, optimize, etc. The idea here is that I'm kind of 'abusing' an autoencoder (ha!) to do a form of image translation. (It's actually a lot like pixel-wise classification, but basically used to "colourize" parts of an image.) I'm guessing that I'll just use what is normally called 'labels' as my 'valid' data(??)
Anyway, an example of this kind of thing would be helpful.

ps - I do realize that auto-encoders would typically validate on the inputs; this is just a specialized application of the underlying idea.

**Comment by utkuozbulak** [comment]
Thats true. Also, the amount of variables you can return are not limited to two. You can return as many as you want. Personally, I usually return image name and sometimes even the image location. Perhaps I should mention it in the tutorials as well.
