### ISSUE TITLE
HELP~~~Could you please upload the Code that you get the mnist_labels.csv

### ISSUE THREAD

**Issue by WanQianSucceed** [utkuozbulak/pytorch-custom-dataset-examples#5]
Awesome work!
After reading your article, I have benefited a lot.  I am interseted in how did you get the mnist_labels.csv. Did you get the mnist_labels.csv by using MATLAB? 
I will be very grateful if you can upload the code.

Looking for your reply.

**Comment by utkuozbulak** [comment]
Hey,

I actually don't remember if it was in that format or I created it myself for ease of use, haven't used MNIST in a long while myself.

Still, I uploaded the whole train/test dataset as well as train/test.csv for the labels to dropbox. I hope it works out for you.

https://www.dropbox.com/s/vc14b2cl9dz3kab/mnist_train_test.tar?dl=0

**Comment by WanQianSucceed** [comment]
I am doing similar work, so I want to get that file. Anyway, thank you very much.
Appreciate~
