### ISSUE TITLE
Future Updates suggestion

### ISSUE THREAD

**Issue by Ceveloper** [utkuozbulak/pytorch-custom-dataset-examples#6]
Your explanation was very good and very short, amazing. For future updates, I would suggest a custom dataset example in which __getitem() does return more than one image showing how to choose the images based on the labels in the .csv file (ex. image retrieval).

**Comment by 5l1v3r1** [comment]
well this is an elementary level repo so dont expect much out of it.

**Comment by utkuozbulak** [comment]
Hey, it is not too hard to have these cases once you understand how datasets work. As such, I would like to keep the examples simple so that people who just started playing with pytorch are not overwhelmed.

**Comment by Nevermetyou65** [comment]
Can you do this for text data with random augmentation as well, sir?
